<?php
namespace app\merchant\controller;

use app\common\controller\CrudController;
use support\Request;
use support\Response;

class MenuController extends CrudController {

    public function get(Request $request): Response {
        $this->output = $this->_default();
        return $this->success();
    }

    private function _default() {
        // 数组格式菜单
        return  [
            [
                "id" => 3,
                "title" => "权限管理",
                "icon" => "layui-icon layui-icon-vercode",
                "key" => "auth",
                "pid" => 0,
                "href" => "",
                "type" => 0,
                "weight" => 900,
                "status" => 1,
                "created_at" => "2024-08-08 08:00:00",
                "updated_at" => "2024-08-08 08:00:00",
                "name" => "权限管理",
                "value" => 3,
                "children" => [
                    [
                        "id" => 4,
                        "title" => "账户管理",
                        "icon" => "",
                        "key" => "app\\admin\\controller\\AdminController",
                        "pid" => 3,
                        "href" => "/admin/admin/index",
                        "type" => 1,
                        "weight" => 1000,
                        "status" => 1,
                        "created_at" => "2024-08-08 08:00:00",
                        "updated_at" => "2024-08-08 08:00:00",
                        "name" => "账户管理",
                        "value" => 4,
                        "children" => [],
                    ],
                    [
                        "id" => 5,
                        "title" => "角色管理",
                        "icon" => "",
                        "key" => "app\\admin\\controller\\RoleController",
                        "pid" => 3,
                        "href" => "/admin/role/index",
                        "type" => 1,
                        "weight" => 900,
                        "status" => 1,
                        "created_at" => "2024-08-08 08:00:00",
                        "updated_at" => "2024-08-08 08:00:00",
                        "name" => "角色管理",
                        "value" => 5,
                        "children" => [],
                    ],
                    [
                        "id" => 6,
                        "title" => "菜单管理",
                        "icon" => "",
                        "key" => "app\\admin\\controller\\RuleController",
                        "pid" => 3,
                        "href" => "/admin/rule/index",
                        "type" => 1,
                        "weight" => 800,
                        "status" => 1,
                        "created_at" => "2024-08-08 08:00:00",
                        "updated_at" => "2024-08-08 08:00:00",
                        "name" => "菜单管理",
                        "value" => 6,
                        "children" => [],
                    ],
                ],
            ],
            [
                "id" => 9,
                "title" => "通用设置",
                "icon" => "layui-icon layui-icon-set",
                "key" => "common",
                "pid" => 0,
                "href" => "",
                "type" => 0,
                "weight" => 700,
                "status" => 1,
                "created_at" => "2024-08-08 08:00:00",
                "updated_at" => "2024-08-08 08:00:00",
                "name" => "通用设置",
                "value" => 9,
                "children" => [
                    [
                        "id" => 10,
                        "title" => "个人资料",
                        "icon" => "",
                        "key" => "app\\admin\\controller\\AccountController",
                        "pid" => 9,
                        "href" => "/admin/account/index",
                        "type" => 1,
                        "weight" => 800,
                        "status" => 1,
                        "created_at" => "2024-08-08 08:00:00",
                        "updated_at" => "2024-08-08 08:00:00",
                        "name" => "个人资料",
                        "value" => 10,
                        "children" => [],
                    ],
                    [
                        "id" => 114,
                        "title" => "配置管理",
                        "icon" => "",
                        "key" => "app\\admin\\controller\\ConfigController",
                        "pid" => 9,
                        "href" => "/admin/config/list",
                        "type" => 1,
                        "weight" => 500,
                        "status" => 1,
                        "created_at" => "2024-08-08 08:00:00",
                        "updated_at" => "2024-08-08 08:00:00",
                        "name" => "配置管理",
                        "value" => 114,
                        "children" => [],
                    ],
                    [
                        "id" => 115,
                        "title" => "系统配置",
                        "icon" => "",
                        "key" => "app\\admin\\controller\\ConfigController@config",
                        "pid" => 9,
                        "href" => "/admin/config/index",
                        "type" => 1,
                        "weight" => 400,
                        "status" => 1,
                        "created_at" => "2024-08-08 08:00:00",
                        "updated_at" => "2024-08-08 08:00:00",
                        "name" => "系统配置",
                        "value" => 115,
                        "children" => [],
                    ],
                    [
                        "id" => 149,
                        "title" => "操作日志",
                        "icon" => "",
                        "key" => "app\\admin\\controller\\LogController",
                        "pid" => 9,
                        "href" => "/admin/log/index",
                        "type" => 1,
                        "weight" => 300,
                        "status" => 1,
                        "created_at" => "2024-10-24 14:15:29",
                        "updated_at" => "2024-10-24 14:22:04",
                        "name" => "操作日志",
                        "value" => 149,
                        "children" => [],
                    ],
                ],
            ],
        ];
    }
}